source(paste0(gsub("\\/bat","",tryCatch(dirname(rstudioapi::getActiveDocumentContext()$path),error=function(e){getwd()})),'/Model_library/config_vdatabase_yck_major_info/config_add.R',sep=""),echo=TRUE,encoding="utf-8")
source(paste0(gsub("\\/bat","",tryCatch(dirname(rstudioapi::getActiveDocumentContext()$path),error=function(e){getwd()})),'/main/main_che300.R',sep=""),echo=TRUE,encoding="utf-8")
source(paste0(gsub("\\/bat","",tryCatch(dirname(rstudioapi::getActiveDocumentContext()$path),error=function(e){getwd()})),'/main/main_wash.R',sep=""),echo=TRUE,encoding="utf-8")
####ID_match
source(paste0(gsub("\\/bat","",tryCatch(dirname(rstudioapi::getActiveDocumentContext()$path),error=function(e){getwd()})),'/config/config_plat_id_match/code/main_plat_id.R',sep=""),echo=TRUE,encoding="utf-8")
####highLight
source(paste0(gsub("\\/bat","",tryCatch(dirname(rstudioapi::getActiveDocumentContext()$path),error=function(e){getwd()})),'/Model_library/hl_config_che300/hl_config_che300.R',sep=""),echo=TRUE,encoding="utf-8")
#source(paste0(gsub("\\/bat","",tryCatch(dirname(rstudioapi::getActiveDocumentContext()$path),error=function(e){getwd()})),'/Model_library/Model_library_autohome/yck_autohome_match.R',sep=""),echo=TRUE,encoding="utf-8")
source(paste0(gsub("\\/bat","",tryCatch(dirname(rstudioapi::getActiveDocumentContext()$path),error=function(e){getwd()})),'/main/main_detail/series/config_series_id_match.R',sep=""),echo=TRUE,encoding="utf-8")
source(paste0(gsub("\\/bat","",tryCatch(dirname(rstudioapi::getActiveDocumentContext()$path),error=function(e){getwd()})),'/main/main_detail/series/czw12365.R',sep=""),echo=TRUE,encoding="utf-8")